In [2]:
import pandas as pd
import numpy as np

In [11]:
hotel = pd.read_excel('./../data/hotel_list_origin.xlsx', header=1)

In [12]:
hotel

,번호,지역1\n(시도),지역2\n(시군구),업종,호텔명(등록명칭),관광사업자명\n(법인명 or 개인명),영업상태\n(19.12.31기준),현행 호텔등급,Unnamed: 8,시설개요,Unnamed: 10,Unnamed: 11,객실수,주소(도로명주소),부대시설
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,등급,등급부여일,층수(지하~지상),대지면적\n(㎡),건축연면적\n(㎡),NaN,NaN,NaN
1,1.0,강원,춘천시,관광호텔,춘천세종관광호텔,주식회사 세종,영업중,3성급,2020.03.17,지하1층~지상3층,9352,4878,63,춘천시 봉의동 15-3,"식당, 연회장, 헬스장"
2,2.0,강원,춘천시,관광호텔,춘천베어스관광호텔,유한회사 화성에이에스엠,영업중,기간만료,NaN,지하1층~지상5층,8985,8680,78,춘천시 삼천동 300-3,"식당, 웨딩홀, 연회장"
3,3.0,강원,원주시,관광호텔,(주)호텔인터불고 원주,(주)호텔인터불고원주,영업중,신청중,NaN,지하2층~지상8층,26215,26377.55,152,원주시 동부순환로 200(반곡동),"대연회장, 중연회장, 헬스클럽, 수영장, \n사우나, 레스토랑, 유흥주점, 스카이라..."
4,4.0,강원,원주시,관광호텔,베니키아문막호텔,주식회사 해평,휴업,3성급,2020.12.28,지하1층~지상9층,1256,4118.58,66,원주시 문막읍 왕건로 9,"라이브바, 연회장"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2297,2297.0,경상북도,영덕군,휴양콘도미니엄업,오션비치 휴양콘도미니엄,㈜오션비치,영업중,NaN,NaN,지상5층,11556,3618.69,58,경상북도 영덕군 강구면 동해대로 4265-43 (오션뷰컨트리클럽),"야외수영장, 편의점, 비즈니스 룸, 스크린골프연습장, 세미나실(연회장), 교육 및 ..."
2298,2298.0,경상북도,울진군,휴양콘도미니엄업,한화호텔&리조트㈜,문석,영업중,NaN,NaN,지상9층,28202.45,240,250,경북 울진군 온정면 온천로 129-13,"사우나, 수영장, 일반음식점, 노래방, 당구장"
2299,2299.0,경상북도,울진군,휴양콘도미니엄업,덕구온천콘도,강윤석,영업중,NaN,NaN,지상5층,5282,7000,74,경북 울진군 북면 덕구온천로 921,"사우나, 일반음식점"
2300,2300.0,인천광역시,중구,휴양콘도미니엄업,THEWEEK&,휴업중,8층(지하2층~지상6층),7000,32945,0,201,인천 중구 용유서로 379,02-6900-5336,"수영장,편의점,레스토랑",NaN
2301,2301.0,인천광역시,옹진군,휴양콘도미니엄업,마린프라자,휴업중,6,20818,11774.9,0,0,옹진군 자월면 승봉로29번길 17-41,032-832-1818,NaN,NaN

In [15]:
hotel.columns = ['idx', 'addr1', 'addr2', 'type', 'name', 'biz_name', 'status', 'rate', 'rate_date', 'floor', 'area1', 'area2', 'rooms', 'address', 'amenities']

In [18]:
hotel

,idx,addr1,addr2,type,name,biz_name,status,rate,rate_date,floor,area1,area2,rooms,address,amenities
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,등급,등급부여일,층수(지하~지상),대지면적\n(㎡),건축연면적\n(㎡),NaN,NaN,NaN
1,1.0,강원,춘천시,관광호텔,춘천세종관광호텔,주식회사 세종,영업중,3성급,2020.03.17,지하1층~지상3층,9352,4878,63,춘천시 봉의동 15-3,"식당, 연회장, 헬스장"
2,2.0,강원,춘천시,관광호텔,춘천베어스관광호텔,유한회사 화성에이에스엠,영업중,기간만료,NaN,지하1층~지상5층,8985,8680,78,춘천시 삼천동 300-3,"식당, 웨딩홀, 연회장"
3,3.0,강원,원주시,관광호텔,(주)호텔인터불고 원주,(주)호텔인터불고원주,영업중,신청중,NaN,지하2층~지상8층,26215,26377.55,152,원주시 동부순환로 200(반곡동),"대연회장, 중연회장, 헬스클럽, 수영장, \n사우나, 레스토랑, 유흥주점, 스카이라..."
4,4.0,강원,원주시,관광호텔,베니키아문막호텔,주식회사 해평,휴업,3성급,2020.12.28,지하1층~지상9층,1256,4118.58,66,원주시 문막읍 왕건로 9,"라이브바, 연회장"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2297,2297.0,경상북도,영덕군,휴양콘도미니엄업,오션비치 휴양콘도미니엄,㈜오션비치,영업중,NaN,NaN,지상5층,11556,3618.69,58,경상북도 영덕군 강구면 동해대로 4265-43 (오션뷰컨트리클럽),"야외수영장, 편의점, 비즈니스 룸, 스크린골프연습장, 세미나실(연회장), 교육 및 ..."
2298,2298.0,경상북도,울진군,휴양콘도미니엄업,한화호텔&리조트㈜,문석,영업중,NaN,NaN,지상9층,28202.45,240,250,경북 울진군 온정면 온천로 129-13,"사우나, 수영장, 일반음식점, 노래방, 당구장"
2299,2299.0,경상북도,울진군,휴양콘도미니엄업,덕구온천콘도,강윤석,영업중,NaN,NaN,지상5층,5282,7000,74,경북 울진군 북면 덕구온천로 921,"사우나, 일반음식점"
2300,2300.0,인천광역시,중구,휴양콘도미니엄업,THEWEEK&,휴업중,8층(지하2층~지상6층),7000,32945,0,201,인천 중구 용유서로 379,02-6900-5336,"수영장,편의점,레스토랑",NaN
2301,2301.0,인천광역시,옹진군,휴양콘도미니엄업,마린프라자,휴업중,6,20818,11774.9,0,0,옹진군 자월면 승봉로29번길 17-41,032-832-1818,NaN,NaN

In [21]:
# 5, 5성 > 5성급

df = hotel.replace({
    'rate': {'5성': '5성급', '5': '5성급', '4성': '4성급', '4': '4성급', '3': '3성급', '3성': '3성급', '2성': '2성급', '2': '2성급',
             '1성': '1성급', '1': '1성급', '1등급': '1성급', '2등급': '2성급'}
})

In [25]:
# status(일일상태) - 휴업, rate(등급) - 5, 4, 3, 2, 1성급
df =  df[(df['rate'].isin(['5성급', '4성급', '3성급', '2성급', '1성급'])) & (df['status'].isin(['영업중']))]

In [30]:
# 723 rows, 15 cols
df.shape

(723, 15)

In [35]:
group_df = df.groupby(['addr1', 'rate']).head(5).sort_values(by=['addr1', 'rate'], ascending=[True, False])

In [41]:
# rows : 286

group_df[['addr1', 'addr2', 'rate', 'type', 'rooms']].to_csv('시도별_호텔등급확인_20211124.csv', encoding='utf-8-sig')

In [40]:
group_df.to_csv('시도별_호텔등급_확인.csv', encoding='utf-8-sig')